[package]
name = "nwp-web"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
base64 = "0.22"
csv = "1"
encoding_rs = "0.8"
gloo-net = "0.6"
js-sys = "0.3"
leptos = { version = "0.8.20", features = ["csr"] }
leptos_router = "0.8"
markdown_view_leptos = "0.1.92"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Blob", "DataTransfer", "Document", "DomRect", "DomTokenList", "DragEvent", "Element", "File", "FileList", "History", "HtmlAnchorElement", "HtmlAudioElement", "HtmlElement", "HtmlInputElement", "HtmlMediaElement", "Location", "ScrollBehavior", "ScrollIntoViewOptions", "ScrollLogicalPosition", "Storage", "Url", "Window"] }
